apiVersion: v1
kind: Service
metadata:
  name: local-storage-exporter-service
  labels:
    app: local-storage-exporter
spec:
  selector:
    app: local-storage-exporter
  ports:
    - protocol: TCP
      name: metrics
      port: 9100
      targetPort: metrics