storageClassNames: []
storagePath:

metricsPort: 9100
serviceEnabled: false
updateInterval: 30s

serviceMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s
podMonitor:
  enabled: false
  interval: 30s
  scrapeTimeout: 10s

imagePullPolicy: IfNotPresent
imagePullSecrets: []
repository: 
tag: latest

daemonSet:
  enable: false

deployment:
  enable: true
  replicas: 1