name: Docker Image CI

on:
  workflow_dispatch:
  push:
   branches: [ "main" ]
   paths:
      - "local_storage_exporter/**"
      - "Dockerfile"
      - ".dockerignore"
      - "pyproject.toml"
      - "uv.lock"
      
  pull_request:
    branches: [ "main" ]
    paths:
      - "local_storage_exporter/**"
      - "Dockerfile"
      - ".dockerignore"
      - "pyproject.toml"
      - "uv.lock"

env:
  ARTIFACT_REGISTRY_PATH: ${{ secrets.GCP_ARTIFACT_REGISTRY_PATH }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Auth GCloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Docker Login to Google Artifact Registry
      uses: docker/login-action@v3
      with:
        registry: europe-west3-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_SA_KEY }}

    - name: Build the Docker image
      run: |
        set -euo pipefail

        # Define the image name and tag
        IMAGE_NAME="${{ env.ARTIFACT_REGISTRY_PATH }}/local-storage-exporter"
        IMAGE_TAG=$(date +%Y%m%d%H%M%S)
        COMMIT_TAG="commit-${{ github.sha }}"
        
        echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
        docker build . -f Dockerfile -t $IMAGE_NAME:$IMAGE_TAG
        
        echo "Tagging Docker image with latest and commit tags"
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
        docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$COMMIT_TAG
        
        echo "Pushing Docker images to Artifact Registry: ${{ env.ARTIFACT_REGISTRY_PATH }}"
        docker push $IMAGE_NAME:$IMAGE_TAG
        docker push $IMAGE_NAME:$COMMIT_TAG
        docker push $IMAGE_NAME:latest
